### ISSUE TITLE
Changes in code

### ISSUE THREAD

**Issue by druppy** [ybbus/jsonrpc#19]
Hi  ...

First, thanks for a really nice jsonrpc module, it has been quite useful for me. I really like to know what your plans are with this module and if you have any plan for versioning it somehow (not the strongest part of go pkg).

I ran into a situation where some of my code has stopped working as the module changes API, and I like to know if there are more plans for changes in the future ?

**Comment by ybbus** [comment]
Hi.

This should not have happened since I already use semver.org versioning.

I did a major release from 1.0 to 2.0 but since all releases are tagged your package manager should be aware of this.

If you use https://github.com/golang/dep for example there shouldn't be a problem since it is aware of semver tagged releases

**Comment by ybbus** [comment]
If you go here: https://github.com/ybbus/jsonrpc/tags

You should see that release commits are correctly tagged using semver.

**Comment by druppy** [comment]
Thanks, about time I take a look into deb, I hope this soon will become part of the official tool set.

The above versioning sounds like all I could hope for, deb ... here I come :-)
