### ISSUE TITLE
 Result property type in RPCResponse structure. At least for CallFor method.

### ISSUE THREAD

**Issue by cv21** [ybbus/jsonrpc#26]
We have the GetObject method for RPCResponse and here we can find that we do marshal+unmarshal for conversion to custom response structure.
```go
func (RPCResponse *RPCResponse) GetObject(toType interface{}) error {
	js, err := json.Marshal(RPCResponse.Result)
	if err != nil {
		return err
	}

	err = json.Unmarshal(js, toType)
	if err != nil {
		return err
	}

	return nil
}
```

It could be better if we will use json.RawBytes as a type of Result property.
It means that we will have more efficient code:
```go
func (RPCResponse *RPCResponse) GetObject(toType interface{}) error {
	err = json.Unmarshal(RPCResponse.Result, toType)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by ybbus** [comment]
Hi.

I got your point, but I think, this would be a breaking change, since RPCResponse.Result is exposed.

You would also have a problem if you directly want to check if Result is nil, right?
Also GetInt()... etc would have to change.

If you have a feasable idea, just let me know or raise a PR. But with a breaking change, this cannot be done under the major version.

**Comment by cv21** [comment]
> You would also have a problem if you directly want to check if Result is nil, right?
We can use `*json.RawMessage`, it is not a problem.

> Also GetInt()... etc would have to change.
Sure, it is. But the Interface will be the same.

> But with a breaking change, this cannot be done under the major version.
Yes, we can schedule that changes as part of next major version.

**Comment by ybbus** [comment]
Hi cv21,

just looked into it.
The problem with json.RawMessage is, that for example on string result, the output of:

```golang
type RPCResponse struct {
	Result interface{} `json:"result"`
}

func main() {
	personJson := []byte(`{"result": "Alex"}`)
	var rpcResponse *RPCResponse
	json.Unmarshal(personJson, &rpcResponse)
	fmt.Println(rpcResponse.Result)
	fmt.Println(reflect.TypeOf(rpcResponse.Result))
}
```
Is "Alex" and type "RawMessage", while using the old way, the output is Alex (without quotes) and string.

So you always would need to marshall the result before being able to use it, right?
But I mean, this will anyway be done most of the time using the helper functions because you will not directly continue work with the interface type.
